### ISSUE TITLE
Thinking With Your Hands: Sketching For Software Development (Hamburg)

### ISSUE THREAD

**Issue by afknapping** [afknapping/workshops#1]
![scan](https://cloud.githubusercontent.com/assets/170145/13792945/b686d6ca-eaf4-11e5-911c-d33be7184e9c.jpg)

---

⚡️ Location and ☕️ sponsored by

[![ubilabs_logo_h 1](https://cloud.githubusercontent.com/assets/170145/14232419/9902f078-f9ab-11e5-8618-703f31f0ad45.png)](http://ubilabs.net/jobs)

---
## Why should I learn sketching?

> Sketching is not about being a good artist. It's about being a good thinker. 

—[Jason Santa Maria](http://v4.jasonsantamaria.com/articles/pretty-sketchy/)

> The real goal of sketching is functional. It’s about generating ideas, solving problems, and communicating ideas more effectively with others.

—[Jared Spool](https://articles.uie.com/why_sketching/)

Expressing solutions in words is difficult. For the other person to understand what you mean is even more difficult. That is why we take screenshots when the interface is broken, instead of describing the bug in words.

Sketching is like taking screenshots of your thoughts:
- _You_ understand better what you mean
- _Others_ understand better what you mean
- _Understanding_ across people, roles and teams is reached much faster

In consequence, sketching safes a lot of time and avoids frustration. You might know The Project Cartoon:

![ba7a7dfc-d714-11e5-9b07-524b29a65ff8](https://cloud.githubusercontent.com/assets/170145/13728893/277877be-e927-11e5-9a5d-d77e3f03c53a.png)

Sketching can help a great deal to avoid situations like this. By clearing out misunderstandings _before_ they are crafted into code, sketching can help to safe money, time and stress.
## What exactly will I learn in this workshop?

The goal of this workshop is mostly to ease the fear of pen and paper and install sketching as a new communication default in the brain. That includes:
- receiving and giving feedback
- materials and tools
- basic shapes
- typography
- icons
- color and shade
- diagrams
- interfaces
- posters
## What do I need to know, own or prepare to attend?

Nothing. You will be equipped with all necessary tools, materials, knowledge and coffee :rocket:
## Who should attend?

Everybody who is working in Software can attend to improve communication in their teams:
- Developers
- Designers
- Product Owners
- Project Managers
- Community Stewards
- Event Organizers
- Supporters

---
## Next date: Saturday April 9th 2016, 10:00 – 15:00
- (includes 1 hr lunchbreak)
- **Location:** Hamburg, tba
- 🎉 **Price: Nearly free!** 🎉 I will collect Eur 29 per person to pay for tools and materials.  
  For those who cannot afford the 29 Euro, there will be at least 3 inclusivity tickets available at the price of 0 Eur. You can apply for those by writing to fabian at superpursuitmo.de – I will keep that info confidential, of course!
## How do I reserve a seat?

please leave a comment here so I can notify you wenn tickets are availabe. if in doubt, a "+1" does it :)

if you do not have a github account, either create one at [github.com/join](https://github.com/join) or or tell me via **fabian at superpursuitmo.de**

**Please let me know if would you be interested in childcare while attending the workshop!**

**Comment by filtercake** [comment]
test

**Comment by herzi** [comment]
+2

**Comment by nilswindisch** [comment]
Dienstreiseantrag ist eingeleitet :)

**Comment by cinocode** [comment]
+1

**Comment by ptrwllrt** [comment]
(+1 for a berlin version)

**Comment by rarspace01** [comment]
+1

**Comment by sssggr** [comment]
+1

**Comment by andrecedik** [comment]
+1

**Comment by maxzender** [comment]
+1 :+1:

**Comment by flooose** [comment]
+1

**Comment by dorotheelaugwitz** [comment]
+1

**Comment by maiwald** [comment]
+1

**Comment by GJacobsohn** [comment]
+1

**Comment by Catrin** [comment]
+1

**Comment by loettz** [comment]
+1

**Comment by blindgaenger** [comment]
+1

**Comment by HerrBertling** [comment]
+1

**Comment by teresaholfeld** [comment]
+1

**Comment by marius-be** [comment]
+1

**Comment by mustaphazorgati** [comment]
+1

**Comment by ellenschwartau** [comment]
+1

**Comment by PeterPannsen** [comment]
+1

**Comment by Strassenkatze** [comment]
+1

**Comment by afknapping** [comment]
Hey everyone!

Great to see so many people interested in this ♥️ 🚀

I can reveal a missing detail today: the location. **[Ubilabs](http://ubilabs.net) will provide us with space to learn and coffee to drink!** Thanks a lot to everyone involved, especially @KlausTrainer for making it happen! He is btw looking for team mates :) 👉 [ubilabs.net/jobs](http://ubilabs.net)

I will post a link to click your tickets some time next week.

Until then, enjoy the Easter holidays with your loved ones! 🐰🐣

Fabian

**Comment by afknapping** [comment]
Hey all.

⚡️ Tickets will be available tonight (Sunday) 22:00 at... ⚡️

#### 👉 https://ti.to/filtercake-workshops/thinking-with-your-hands-16-04-09 👈

♥️ Please note that accepting and following the [Code of Conduct](http://berlincodeofconduct.org/) will be mandatory to participate ♥️

Looking forward to meet you next Saturday!

Fabian

**Comment by afknapping** [comment]
PS: **due to payment provider constraints which I cannot influence, only PayPal is available as payment method this time :(**

**Comment by flooose** [comment]
According to the site "Registration is not currently available." Is this a temporary thing, or is the class full?

**Comment by afknapping** [comment]
@flooose all seats gone, sorry :/

i will announce the next date in this thread when it's planned....

**Comment by afknapping** [comment]
![](https://pbs.twimg.com/media/CfviFcsWQAAVHZb.jpg)

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Saturday workshop was ✨✨ <br><br>thx <a href="https://twitter.com/ubilabs">@ubilabs</a> + attendees for all the awesome &lt;3<br><br>Berlin edition 👉 <a href="https://t.co/XgYhyBuy5u">https://t.co/XgYhyBuy5u</a> <a href="https://t.co/C99B7wctYh">pic.twitter.com/C99B7wctYh</a></p>&mdash; CSS3EE (@filtercake) <a href="https://twitter.com/filtercake/status/719417150679740417">April 11, 2016</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

---

So the [next edition will take place in Berlin](https://github.com/filtercake/workshops/issues/2).

I'll close this ticket for now, but plan to...
- post a review here once I wrote it
- post info here about when the workshop will happen in Hamburg again

See you then! 🚀
